Some mini-changes #2
mastercoms/tf2cfg pull request #118
Opened 2019-09-02 17:41 UTC by Perkzitos

I removed the `alias download download_mapsonly` beucase I think people will prefer to set it via menu instead of using the `modules.cfg` file. This is useful for people that play on community servers, like Freak Fortress 2 servers.

2019-09-03 01:06 UTC, mastercoms requested changes

2019-09-03 01:06 UTC, mastercoms commented on config/mastercomfig/cfg/comfig/comfig.cfg
> +
No need for a line here.

2019-09-03 01:06 UTC, mastercoms commented on config/mastercomfig/cfg/comfig/comfig.cfg
> -alias download download_mapsonly
I set it by default because I haven't seen any complaints about it, but have seen complaints the other way (https://www.teamfortress.tv/52468/dm-server-jointime-fix).

2019-09-03 01:06 UTC, mastercoms commented on config/mastercomfig/cfg/comfig/comfig.cfg
> +tf_spectate_pyrovision 0 // Don't force pyrovision in spectator mode
I don't use quotation marks because it messes with some syntax parses which think it is the start of a string.

2019-09-03 02:29 UTC, Perkzitos commented on config/mastercomfig/cfg/comfig/comfig.cfg
> +
It's just to follow the rest of the aliases.

2019-09-03 02:30 UTC, Perkzitos commented on config/mastercomfig/cfg/comfig/comfig.cfg
> -alias download download_mapsonly
Alright.

2019-09-03 02:30 UTC, Perkzitos commented on config/mastercomfig/cfg/comfig/comfig.cfg
> +tf_spectate_pyrovision 0 // Don't force pyrovision in spectator mode
Ok. But can you change the "xrays" to "x-rays" at least?

2019-09-04 08:50 UTC, merged

2019-09-04 08:50 UTC, mastercoms commented
Thank you for your contribution to mastercomfig!