Update comfig.cfg
mastercoms/tf2cfg pull request #138
Opened 2019-10-07 17:46 UTC by Perkzitos

2019-10-07 20:20 UTC, mastercoms requested changes

2019-10-07 20:20 UTC, mastercoms commented on config/mastercomfig/cfg/comfig/comfig.cfg
> +cl_timeout 60 // Max client timeout
How much better is 60 vs 65?

2019-10-07 20:20 UTC, mastercoms commented on config/mastercomfig/cfg/comfig/comfig.cfg
> +alias packet_rate_congestion "cl_cmdrate 33;cl_updaterate 33;packet_rate_congestion_aliases"
This is intentional. I'm currently experimenting with an off by one error caused by floating point usage in the networking system.

2019-10-07 20:20 UTC, mastercoms commented on config/mastercomfig/cfg/comfig/comfig.cfg
> +//cl_ragdoll_fade_time 5 // Fade out ragdolls in 5 seconds
Having it higher than 5 enables certain ragdoll effects.

2019-10-07 20:20 UTC, mastercoms commented on config/mastercomfig/cfg/comfig/comfig.cfg
> -alias ragdolls_high "cl_ragdoll_fade_time 5.1;cl_ragdoll_forcefade 0;cl_ragdoll_physics_enable 1;ragdoll_sleepaftertime 3.0"
Having a lower time optimizes the ragdolls.

2019-10-07 20:20 UTC, mastercoms commented on config/mastercomfig/cfg/comfig/comfig.cfg
> -alias snapshots snapshots_balanced
This is intentional. I am testing a unified interp again.

2019-10-07 20:55 UTC, Perkzitos commented on config/mastercomfig/cfg/comfig/comfig.cfg
> +cl_timeout 60 // Max client timeout
Less time to disconnect.

2019-10-07 20:57 UTC, Perkzitos commented on config/mastercomfig/cfg/comfig/comfig.cfg
> -alias ragdolls_high "cl_ragdoll_fade_time 5.1;cl_ragdoll_forcefade 0;cl_ragdoll_physics_enable 1;ragdoll_sleepaftertime 3.0"
Alright, but remove the ".0" from ragdoll_sleepaftertime, it's unnecessary to keep it.

2019-10-08 12:08 UTC, mastercoms commented on config/mastercomfig/cfg/comfig/comfig.cfg
> +cl_timeout 60 // Max client timeout
My thinking is that people can manually disconnect if they want to.

2019-10-08 12:08 UTC, mastercoms approved these changes

2019-10-08 12:09 UTC, mastercoms commented
Thank you for your contribution to mastercomfig!

2019-10-08 12:09 UTC, merged