Miscellaneous changes
mastercoms/tf2cfg pull request #146
Opened 2019-11-18 21:52 UTC by Perkzitos

For cl_ragdoll_fade_time: -1 isn't different from 0 in this specific cvar

For r_eyegloss: Idk if that makes a difference on FPS but here is it.

Please ignore dynamic_background_preload_room.

2019-11-18 21:56 UTC, mastercoms requested changes

2019-11-18 21:56 UTC, mastercoms commented on config/mastercomfig/cfg/comfig/comfig.cfg
> +//r_eyegloss 1 // Enable eye gloss
r_eyegloss is not used

2019-11-19 01:24 UTC, Perkzitos commented on config/mastercomfig/cfg/comfig/comfig.cfg
> +//r_eyegloss 1 // Enable eye gloss
I didn't know about that. Ignore it then.

2019-11-19 05:13 UTC, mastercoms approved these changes

2019-11-19 05:13 UTC, mastercoms commented
Thank you for your contribution to mastercomfig!

2019-11-19 05:13 UTC, merged