Comfig updates
mastercoms/tf2cfg pull request #264
Opened 2020-05-03 21:50 UTC by Perkzitos

2020-05-03 21:52 UTC, mastercoms requested changes

2020-05-03 21:52 UTC, mastercoms commented on config/mastercomfig/cfg/comfig/comfig.cfg
> -sv_lan 1 // Protect local servers
Why remove `sv_lan 1`? People are reporting that hackers are joining their local games.

2020-05-03 22:35 UTC, Perkzitos commented on config/mastercomfig/cfg/comfig/comfig.cfg
> -sv_lan 1 // Protect local servers
A local game is only joinable if you did "Port Forwarding". Otherwise, it is not.

2020-05-03 22:50 UTC, mastercoms commented on config/mastercomfig/cfg/comfig/comfig.cfg
> -sv_lan 1 // Protect local servers
What about UPnP?

2020-05-03 22:51 UTC, mastercoms approved these changes

2020-05-03 22:52 UTC, merged

2020-05-08 00:07 UTC, CrescentSpirit commented on config/mastercomfig/cfg/comfig/comfig.cfg
> -sv_lan 1 // Protect local servers
I can confirm this happened to me personally; two random people joined my local/listen itemtest server out of nowhere. Didn't give them time for any griefing by disconnecting and immediately proceeded to enable the sv_lan cvar. Haven't had any trouble since. Also, I have been using mastercomfig's default network configuration and have never messed with any "Port Forwarding" settings so I'm not sure if that option is actually relevant. In any case, given the circumstances and plentiful evidence, having sv_lan enabled is essential in my opinion, and defaulting to it was a very good (preemptive) move by mastercoms; will save a lot of people from needless scares and confusion 👍