Config updates again
mastercoms/tf2cfg pull request #270
Opened 2020-05-10 00:21 UTC by Perkzitos

2020-05-10 02:53 UTC, mastercoms requested changes

2020-05-10 02:53 UTC, mastercoms commented on config/mastercomfig/cfg/comfig/comfig.cfg
> +r_occluderminarea 2.5 // Get more occluders
Why was this moved into comfig.cfg?

2020-05-10 02:53 UTC, mastercoms commented on config/mastercomfig/cfg/comfig/comfig.cfg
> +rope_averagelight 0 // Simplify rope lighting for weak GPUs, at the cost of a bit of CPU time
Why was this moved into comfig.cfg?

2020-05-10 02:53 UTC, mastercoms commented on config/mastercomfig/cfg/comfig/comfig.cfg
> +mat_reducefillrate 1 // Simplify material shading and use some DirectX 8 features
Why was this moved out of the lighting module?

2020-05-10 03:00 UTC, Perkzitos commented on config/mastercomfig/cfg/comfig/comfig.cfg
> +r_occluderminarea 2.5 // Get more occluders
You did add "exec  addons/badgpu.cfg" and then I removed it, so I added the values back but replacing the original values from the config. I thought you wanted to overlap the original values with the badgpu addon values. I will undo these changes.

2020-05-10 03:00 UTC, Perkzitos commented on config/mastercomfig/cfg/comfig/comfig.cfg
> +rope_averagelight 0 // Simplify rope lighting for weak GPUs, at the cost of a bit of CPU time
You did add "exec  addons/badgpu.cfg" and then I removed it, so I added the values back but replacing the original values from the config. I thought you wanted to overlap the original values with the badgpu addon values. I will undo these changes.

2020-05-10 03:00 UTC, Perkzitos commented on config/mastercomfig/cfg/comfig/comfig.cfg
> +mat_reducefillrate 1 // Simplify material shading and use some DirectX 8 features
You did add "exec  addons/badgpu.cfg" and then I removed it, so I added the values back but replacing the original values from the config. I thought you wanted to overlap the original values with the badgpu addon values. I will undo these changes.

2020-05-10 03:06 UTC, mastercoms commented on config/mastercomfig/cfg/comfig/comfig.cfg
> +r_occluderminarea 2.5 // Get more occluders
The thing is, exec only works if the user has the addon installed.

2020-05-10 03:09 UTC, Perkzitos commented on config/mastercomfig/cfg/comfig/comfig.cfg
> +r_occluderminarea 2.5 // Get more occluders
Yes but we already have a thing to execute addons.

https://github.com/mastercomfig/mastercomfig/blob/release/dev/presets/package.sh#L27
https://github.com/mastercomfig/mastercomfig/blob/release/dev/addons/package.sh

2020-05-10 03:12 UTC, mastercoms commented on config/mastercomfig/cfg/comfig/comfig.cfg
> +r_occluderminarea 2.5 // Get more occluders
That executes after modules. I want to make Bad GPU set lighting_ex=low.

2020-05-10 04:12 UTC, Perkzitos commented on config/mastercomfig/cfg/comfig/comfig.cfg
> +r_occluderminarea 2.5 // Get more occluders
Done.

2020-05-10 04:31 UTC, mastercoms requested changes

2020-05-10 04:31 UTC, mastercoms commented on dev/presets/package.sh
> +            echo "exec comfig/addons.cfg" >> $autoexec_file
I am planning a different solution for this. No need to have it in this PR.

2020-05-10 04:31 UTC, mastercoms commented on config/cfg/addons/badgpu.cfg
> +lighting_ex=low // Disable lightmap filtering and phong
Please revert this. I have a different solution for this.

2020-05-10 05:03 UTC, Perkzitos commented on config/cfg/addons/badgpu.cfg
> +lighting_ex=low // Disable lightmap filtering and phong
And what about the transparent viewmodels update?

2020-05-10 07:15 UTC, mastercoms commented on config/cfg/addons/badgpu.cfg
> +lighting_ex=low // Disable lightmap filtering and phong
Transparent viewmodels require running those commands directly. We can't use modules, since that allows the user to override it and then transparent viewmodels won't work.

2020-05-10 17:00 UTC, Perkzitos commented
Done @mastercoms

2020-05-11 11:26 UTC, mastercoms approved these changes

2020-05-11 11:26 UTC, merged