Mention -arbmode launch option
mastercoms/tf2cfg pull request #281
Opened 2020-05-24 03:42 UTC by ghost-420

2020-05-24 15:50 UTC, mastercoms commented
Could you detail your findings with -arbmode to back up the description? (here, not in the contribution, so I can know whether to approve it or not)

2020-05-24 18:15 UTC, ghost-420 commented
Routes kGLM* functions through ARB instead of GLSL.
ARB is a faster method, but supports less OpenGL features; I haven't seen graphical rendering mishaps from using it for TF2.
It seems NVIDIA specific with the improvements, `amdgpu` driver is margin of error, but there's no code to show that it's ignored for non-NVIDIA.

`-glmdualshaders` launch option is supposed to switch between kGLMGLSL and kGLMARB in-game if you hold down the Shift key, but has its keybinding disabled.

2020-05-25 15:52 UTC, mastercoms requested changes

2020-05-25 15:52 UTC, mastercoms commented on docs/customization/launch_options.md
> +    * **-arbmode** : set ToGL's drawing language to ARB instead of the default GLSL, less frame variance and higher FPS on NVIDIA; forces fast [clipping](https://developer.valvesoftware.com/wiki/Clip
Can you put the two launch options together, if they're meant to be used together?

2020-05-25 15:52 UTC, mastercoms commented on docs/customization/launch_options.md
> +    * **-arbmode** : set ToGL's drawing language to ARB instead of the default GLSL, less frame variance and higher FPS on NVIDIA; forces fast [clipping](https://developer.valvesoftware.com/wiki/Clip
That fast clipping link is not accurate, please remove it.

2020-05-25 15:52 UTC, mastercoms commented on docs/customization/launch_options.md
> +    * **-arbmode** : set ToGL's drawing language to ARB instead of the default GLSL, less frame variance and higher FPS on NVIDIA; forces fast [clipping](https://developer.valvesoftware.com/wiki/Clip
Software clipping may cause performance issues as well.

2020-05-25 15:52 UTC, mastercoms commented on docs/customization/launch_options.md
> +    * **-arbmode** : set ToGL's drawing language to ARB instead of the default GLSL, less frame variance and higher FPS on NVIDIA; forces fast [clipping](https://developer.valvesoftware.com/wiki/Clip
Change fast clipping to software clipping, so that the name is not misleading to average users.

2020-05-25 15:52 UTC, mastercoms commented on docs/customization/launch_options.md
> +    * **-arbmode** : set ToGL's drawing language to ARB instead of the default GLSL, less frame variance and higher FPS on NVIDIA; forces fast [clipping](https://developer.valvesoftware.com/wiki/Clip
I think it should read `set ToGL to use ARB instead of the default GLSL`.

2020-06-01 20:25 UTC, mastercoms approved these changes

2020-06-01 20:25 UTC, merged

2020-06-01 20:50 UTC, mastercoms commented
Just a heads up, this actually doesn't do anything, because `-glslcontrolflow` forces GLSL on. So if `-arbmode` didn't work without it, that means ARB mode doesn't work, and you were just going back to GLSL.