Limited capture module
mastercoms/tf2cfg pull request #284
Opened 2020-05-24 06:14 UTC by ghost-420

2020-05-24 06:34 UTC, ghost-420 commented
"Turn voice fadeout off" is not meant to be here.

2020-05-24 09:02 UTC, felikcat reviewed
bullet_debree was later corrected to decal_debris

2020-05-24 09:06 UTC, felikcat reviewed
N/A

2020-05-24 15:55 UTC, mastercoms commented on config/mastercomfig/cfg/comfig/comfig.cfg
> +voice_fadeouttime 0 // Meant to fade sound at the tail end of voice data, but causes issues with long voice transmissions.
Can you move this to its own PR?

2020-05-24 16:02 UTC, mastercoms requested changes

2020-05-24 16:02 UTC, mastercoms commented on config/mastercomfig/cfg/comfig/comfig.cfg
> +alias decal_debris_off "fx_drawimpactdebris 0;fx_drawimpactdust 0;fx_drawmetalspark 0"
I think this module is a granular subset of particles. This should wait until we have another system for granular controls.

2020-05-24 16:02 UTC, mastercoms commented on config/mastercomfig/cfg/comfig/comfig.cfg
> +alias decals_art_ultra "r_renderoverlayfragment 1;r_overlayfademax 2930.0f;r_overlayfademin 2680.0f"
Overlay fading isn't enabled by default, and besides, would not be an ultra feature.

2020-05-24 16:02 UTC, mastercoms commented on config/mastercomfig/cfg/comfig/comfig.cfg
> +alias texture_mipmap_off "mat_mipmaptextures 0" // Sharp textures
I don't think disabling mipmapping should be an accessible feature.

2020-05-24 16:02 UTC, mastercoms commented on config/mastercomfig/cfg/comfig/comfig.cfg
> +alias block_stats_reset_on "alias _resetgamestats;alias resetplayerstats"
I'm not sure this fits as a module. Should be another feature.

2020-05-24 16:02 UTC, mastercoms commented on config/mastercomfig/cfg/comfig/comfig.cfg
> +alias tunnel_vision_off "mat_drawTitleSafe 0"
What is the use case for this?

2020-05-24 16:02 UTC, mastercoms commented on config/mastercomfig/cfg/comfig/comfig.cfg
> +alias cpu_dualcore_off "r_threaded_particles 1;r_threaded_renderables 1;snd_mix_async 1"
As far as I am aware, these do not have negative effects on dual cores or single cores. Additionally, `r_threaded_renderables` does nothing.

2020-05-24 16:02 UTC, mastercoms commented on config/mastercomfig/cfg/comfig/comfig.cfg
> +alias voice_buffer_on "voice_buffer_ms 60"
This is too low of a buffer for most pings + variance.

2020-05-24 16:02 UTC, mastercoms commented on config/mastercomfig/cfg/comfig/comfig.cfg
> +alias voice_buffer_off "voice_buffer_ms 0"
What is the use case for turning off the buffer?

2020-05-24 16:10 UTC, ghost-420 commented on config/mastercomfig/cfg/comfig/comfig.cfg
> +alias cpu_dualcore_off "r_threaded_particles 1;r_threaded_renderables 1;snd_mix_async 1"
You sure? That calls BoneSetupNpcsLast, and I've confirmed higher FPS on a E8400 with that at 0 a year ago.

2020-05-24 16:13 UTC, ghost-420 commented on config/mastercomfig/cfg/comfig/comfig.cfg
> +alias decals_art_ultra "r_renderoverlayfragment 1;r_overlayfademax 2930.0f;r_overlayfademin 2680.0f"
I confused that for detaildist, my bad.

2020-05-24 16:19 UTC, ghost-420 commented on config/mastercomfig/cfg/comfig/comfig.cfg
> +alias block_stats_reset_on "alias _resetgamestats;alias resetplayerstats"
Changed to be a separate config.

2020-05-24 16:22 UTC, ghost-420 commented on config/mastercomfig/cfg/comfig/comfig.cfg
> +alias decals_art_ultra "r_renderoverlayfragment 1;r_overlayfademax 2930.0f;r_overlayfademin 2680.0f"
Reverted.

2020-05-24 16:23 UTC, ghost-420 commented on config/mastercomfig/cfg/comfig/comfig.cfg
> +alias voice_buffer_off "voice_buffer_ms 0"
Testing, I have no idea why turning off the buffer caused no problems for me, it might not change anything.

2020-05-24 16:26 UTC, ghost-420 commented on config/mastercomfig/cfg/comfig/comfig.cfg
> +alias texture_mipmap_off "mat_mipmaptextures 0" // Sharp textures
I forgot that disabling mipmapped textures is bad for performance; reverted.

2020-05-24 16:29 UTC, ghost-420 commented on config/mastercomfig/cfg/comfig/comfig.cfg
> +alias voice_buffer_on "voice_buffer_ms 60"
Reverted.

2020-05-24 16:37 UTC, ghost-420 commented on config/mastercomfig/cfg/comfig/comfig.cfg
> +alias tunnel_vision_off "mat_drawTitleSafe 0"
![1590338172](https://user-images.githubusercontent.com/29991266/82759409-1c1ac280-9da2-11ea-9ddc-ffb7b4bbf3c3.png)
Don't know what the use case for it was. Testing aspect ratios?

2020-05-24 16:41 UTC, mastercoms commented on config/mastercomfig/cfg/comfig/comfig.cfg
> +alias tunnel_vision_off "mat_drawTitleSafe 0"
I mean, why would this be a module for people to use?

2020-05-24 16:42 UTC, ghost-420 commented on config/mastercomfig/cfg/comfig/comfig.cfg
> +alias decal_debris_off "fx_drawimpactdebris 0;fx_drawimpactdust 0;fx_drawmetalspark 0"
Reverted.

2020-05-24 16:44 UTC, mastercoms commented on config/mastercomfig/cfg/comfig/comfig.cfg
> +alias cpu_dualcore_off "r_threaded_particles 1;r_threaded_renderables 1;snd_mix_async 1"
The value of `r_threaded_renderables` has no effect on whether or not those functions are called as a parallel task. It's simply blocked from running regardless of what `r_threaded_renderables` is set to on the latest versions of TF2.

2020-05-24 16:45 UTC, mastercoms commented on config/mastercomfig/cfg/comfig/comfig.cfg
> +alias voice_buffer_off "voice_buffer_ms 0"
Probably a combination of your framerate, variance and ping. Also, it's clamped to 1ms.

2020-05-24 16:48 UTC, ghost-420 commented on config/mastercomfig/cfg/comfig/comfig.cfg
> +alias tunnel_vision_off "mat_drawTitleSafe 0"
Do you want it removed?

2020-05-24 16:49 UTC, mastercoms commented on config/mastercomfig/cfg/comfig/comfig.cfg
> +alias tunnel_vision_off "mat_drawTitleSafe 0"
if there's no use case for it, yes

2020-05-24 18:56 UTC, ghost-420 commented on config/mastercomfig/cfg/comfig/comfig.cfg
> +alias cpu_dualcore_off "r_threaded_particles 1;r_threaded_renderables 1;snd_mix_async 1"
Removed `r_threaded_renderables 0`; the E8400 is running OpenBSD currently, so I can't test again to make sure for now.

2020-05-24 18:59 UTC, ghost-420 commented on config/mastercomfig/cfg/comfig/comfig.cfg
> +voice_fadeouttime 0 // Meant to fade sound at the tail end of voice data, but causes issues with long voice transmissions.
Once I use Magit successfully for the first time, yes. Github's web interface is not doing it for me.

2020-05-24 19:02 UTC, ghost-420 commented on config/mastercomfig/cfg/comfig/comfig.cfg
> +alias tunnel_vision_off "mat_drawTitleSafe 0"
I doubt it'd cause problems; removed.

2020-07-09 14:42 UTC, mastercoms commented
@ghost-420 Could you resolve the conflicts? Also, I'd prefer a clean branch without so many commits.

2020-07-12 09:49 UTC, closed without merging