comfig.cfg updates
mastercoms/tf2cfg pull request #292
Opened 2020-05-29 18:12 UTC by Perkzitos

2020-05-29 19:25 UTC, mastercoms requested changes

2020-05-29 19:25 UTC, mastercoms commented on config/mastercomfig/cfg/comfig/comfig.cfg
> -//dsp_enhance_stereo 0 // Disable extra spatial DSP effects and delays
I don't want to force this off, since it is automatically applied with high quality sound when using headphones. Hard to detect for mastercomfig, but easy for the game.

2020-05-29 19:25 UTC, mastercoms commented on config/mastercomfig/cfg/comfig/comfig.cfg
> -//mat_tonemapping_occlusion_use_stencil 0 // Force disable stencil buffer for tonemapping
I don't want to force this off, since it is automatically determined based on the graphics card.

2020-05-29 19:25 UTC, mastercoms commented on config/mastercomfig/cfg/comfig/comfig.cfg
> -//ragdoll_sleepaftertime 1.5 // Wait a reasonable time before sleeping ragdoll physics
I don't think we need to set this with f.

2020-05-29 19:37 UTC, Perkzitos commented on config/mastercomfig/cfg/comfig/comfig.cfg
> -//dsp_enhance_stereo 0 // Disable extra spatial DSP effects and delays
https://www.reddit.com/r/GlobalOffensive/comments/3zqtvm/improved_csgo_sound_why_the_popular_settings_suck/

> **dsp_enhance_stereo** is supposed to 'enhance the stereo effect' for a slight performance hit when set to "1". In general, because digital effects that emulate stereo mixing are a bad idea as they to alter the apparent left-right positioning of sounds, and because it took extra CPU workload, I would set it to "0". But in some limited testing I did before writing this, I couldn't tell any appreciable difference between the two settings, so I suspect Valve has made them the same so that one does not offer a competitive advantage.

2020-05-29 19:39 UTC, mastercoms commented on config/mastercomfig/cfg/comfig/comfig.cfg
> -//dsp_enhance_stereo 0 // Disable extra spatial DSP effects and delays
I notice a difference, and also that's CSGO, which has a different audio engine at this point.

2020-05-29 19:40 UTC, Perkzitos commented on config/mastercomfig/cfg/comfig/comfig.cfg
> -//ragdoll_sleepaftertime 1.5 // Wait a reasonable time before sleeping ragdoll physics
This is not the unique cvar with a `f` on it.
`tf_halloween_kart_*` are also cvars with a `f` on it. By this logic, I conclude that the `f` it is there for nothing.

2020-05-29 19:51 UTC, mastercoms commented on config/mastercomfig/cfg/comfig/comfig.cfg
> -//ragdoll_sleepaftertime 1.5 // Wait a reasonable time before sleeping ragdoll physics
I don't think so, I have looked into it and there's no parsing difference since they are always parsed as floats.

2020-05-29 21:17 UTC, Perkzitos commented on config/mastercomfig/cfg/comfig/comfig.cfg
> -//ragdoll_sleepaftertime 1.5 // Wait a reasonable time before sleeping ragdoll physics
> I don't think so, I have looked into it and there's no parsing difference since they are always parsed as floats.

So why the letter `f` is present?

2020-06-01 17:22 UTC, closed without merging

2020-06-01 17:53 UTC, Perkzitos commented on config/mastercomfig/cfg/comfig/comfig.cfg
> -//ragdoll_sleepaftertime 1.5 // Wait a reasonable time before sleeping ragdoll physics
I will add the letter `f`.

2020-06-01 18:46 UTC, mastercoms commented on config/mastercomfig/cfg/comfig/comfig.cfg
> -//ragdoll_sleepaftertime 1.5 // Wait a reasonable time before sleeping ragdoll physics
Sorry, I thought I responded to this. Probably a stylistic choice or misunderstanding by the developer.

2020-06-01 18:48 UTC, Perkzitos commented on config/mastercomfig/cfg/comfig/comfig.cfg
> -//ragdoll_sleepaftertime 1.5 // Wait a reasonable time before sleeping ragdoll physics
I am doing another PR. I closed this but I will keep my changes here into the another PR.