Manage version in comfig.cfg
mastercoms/tf2cfg pull request #325
Opened 2020-06-22 08:31 UTC by micwoj92

this way echo.cfg doesn't have to be updated

Tested this vpk and it works.

2020-06-22 08:39 UTC, micwoj92 commented on config/mastercomfig/cfg/comfig/comfig.cfg
> +alias date_c"echo June 18 2020"
My proposal is to use ISO 8601

2020-06-23 22:44 UTC, mastercoms commented on config/mastercomfig/cfg/comfig/comfig.cfg
> +alias date_c"echo June 18 2020"
My problem with numeric date formats is that they can cause confusion between users in the United States and other users. So a date format with the month as a word is preferred.

2020-06-23 23:17 UTC, micwoj92 commented on config/mastercomfig/cfg/comfig/comfig.cfg
> +alias date_c"echo June 18 2020"
Oh I understand. But still, is it fine or raher add comma as the bot suggests?

2020-06-24 01:14 UTC, mastercoms commented on config/mastercomfig/cfg/comfig/comfig.cfg
> +alias date_c"echo June 18 2020"
I guess adding a comma is good.

2020-06-24 01:19 UTC, micwoj92 commented on config/mastercomfig/cfg/comfig/comfig.cfg
> +alias date_c"echo June 18 2020"
added

2020-06-28 07:27 UTC, mastercoms requested changes
I don't like how the spacing was removed.

2020-06-28 09:49 UTC, micwoj92 commented
When you alias something to echo then the echo doesn't output the first space, i tried with different whitespace characters and it either didn't work or gave "???" error signs, so in my opinion this was best workaround. Feel free to close if you don't like it.

2020-06-28 10:13 UTC, mastercoms commented
Yeah I think I can manage using the different files for version. Thanks for trying.

2020-06-28 10:13 UTC, closed without merging