Add info about user folder and where to find modules.cfg
mastercoms/tf2cfg pull request #333
Opened 2020-06-26 17:21 UTC by micwoj92

2020-06-26 17:35 UTC, mastercoms requested changes

2020-06-26 17:35 UTC, mastercoms commented on docs/customization/modules.md
> +    If you do not have `user` folder you should create it. Template `modules.cfg` file can be downloaded [here](https://github.com/mastercomfig/mastercomfig/releases/latest/download/modules.cfg)
I don't think the template should be mentioned here.

2020-06-26 17:35 UTC, mastercoms commented on docs/customization/modules.md
> +Modules are used in presets to set quality levels and can also be used in the `tf/cfg/user/modules.cfg` file to customize your config easily without searching for individual console variable values.
I think it should be 
```
can also be used in your very own `tf/cfg/user/modules.cfg` file
```

2020-06-26 17:35 UTC, mastercoms commented on docs/customization/modules.md
> +Modules are used in presets to set quality levels and can also be used in the `tf/cfg/user/modules.cfg` file to customize your config easily without searching for individual console variable values.
I'm not sure if I like `You can find out what modules does your preset use [here](https://github.com/mastercomfig/mastercomfig/tree/release/config/cfg/presets)` over the previous way it was linked.

2020-06-26 17:35 UTC, mastercoms commented on docs/customization/modules.md
> +Modules are used in presets to set quality levels and can also be used in the `tf/cfg/user/modules.cfg` file to customize your config easily without searching for individual console variable values.
I think this works better:

```
To set a custom module level just put it in `user/modules.cfg`. For example:
```

2020-06-26 17:42 UTC, micwoj92 commented on docs/customization/modules.md
> +    If you do not have `user` folder you should create it. Template `modules.cfg` file can be downloaded [here](https://github.com/mastercomfig/mastercomfig/releases/latest/download/modules.cfg)
Should it be in customization instead? it's just so people wont make mistake of having modules.cfg.txt when creating manually

2020-06-26 17:44 UTC, micwoj92 commented on docs/customization/modules.md
> +Modules are used in presets to set quality levels and can also be used in the `tf/cfg/user/modules.cfg` file to customize your config easily without searching for individual console variable values.
done

2020-06-26 17:45 UTC, micwoj92 commented on docs/customization/modules.md
> +Modules are used in presets to set quality levels and can also be used in the `tf/cfg/user/modules.cfg` file to customize your config easily without searching for individual console variable values.
I wanted to specifically add info that you can find default values for presets there. I dont know how to put it in another words.

2020-06-26 17:46 UTC, micwoj92 commented on docs/customization/modules.md
> +Modules are used in presets to set quality levels and can also be used in the `tf/cfg/user/modules.cfg` file to customize your config easily without searching for individual console variable values.
done

2020-06-26 18:15 UTC, mastercoms commented on docs/customization/modules.md
> +    If you do not have `user` folder you should create it. Template `modules.cfg` file can be downloaded [here](https://github.com/mastercomfig/mastercomfig/releases/latest/download/modules.cfg)
If that's the case, then the empty modules file should be linked.

2020-06-26 18:19 UTC, mastercoms commented on docs/customization/modules.md
> +Modules are used in presets to set quality levels and can also be used in the `tf/cfg/user/modules.cfg` file to customize your config easily without searching for individual console variable values.
Ok, then fix the grammatical error, plus [use descriptive text](https://web.dev/link-text/) for the link: `You can find out what module levels your preset uses by [viewing their respective cfg file](https://github.com/mastercomfig/mastercomfig/tree/release/config/cfg/presets).`

2020-06-26 18:41 UTC, micwoj92 commented on docs/customization/modules.md
> +    If you do not have `user` folder you should create it. Template `modules.cfg` file can be downloaded [here](https://github.com/mastercomfig/mastercomfig/releases/latest/download/modules.cfg)
This points to template so users already can see module values and read the inside of file for instruction instead of going back and forth to the docs page. If link would be to emply modules.cfg then it also should be in my opinion generated by packaging scripts. I do not believe this change is needed and the template is much better option.

2020-06-26 18:43 UTC, mastercoms commented on docs/customization/modules.md
> +    If you do not have `user` folder you should create it. Template `modules.cfg` file can be downloaded [here](https://github.com/mastercomfig/mastercomfig/releases/latest/download/modules.cfg)
The template encourages people to go through each option which is non-ideal and also involves editing a text file, rather than creating your own layer on top of mastercomfig as intended. This creates harder upgrade paths when modules change, as it involves redoing your modules.

2020-06-26 18:44 UTC, micwoj92 commented on docs/customization/modules.md
> +Modules are used in presets to set quality levels and can also be used in the `tf/cfg/user/modules.cfg` file to customize your config easily without searching for individual console variable values.
done

2020-06-26 18:49 UTC, micwoj92 commented on docs/customization/modules.md
> +    If you do not have `user` folder you should create it. Template `modules.cfg` file can be downloaded [here](https://github.com/mastercomfig/mastercomfig/releases/latest/download/modules.cfg)
Ah, I understand that point.  I see now that creating modules.cfg and empty file (same as autoexec.cfg) and renaming current modules.cfg to something like templatemodules.cfg as best option. Not sure about what you think about that.

2020-06-28 15:17 UTC, mastercoms commented on docs/customization/modules.md
> +    If you do not have `user` folder you should create it. Template `modules.cfg` file can be downloaded [here](https://github.com/mastercomfig/mastercomfig/releases/latest/download/modules.cfg)
You can remove the sentence for now, and then we can add it back once we have a generator for it.

2020-06-28 15:42 UTC, micwoj92 commented on docs/customization/modules.md
> +    If you do not have `user` folder you should create it. Same principle applies to `modules.cfg` file.
Edited the sentence

2020-06-28 15:46 UTC, mastercoms approved these changes

2020-06-28 15:46 UTC, merged