Add temporary info on how to re-enable chat
mastercoms/tf2cfg pull request #343
Opened 2020-07-01 23:15 UTC by micwoj92

I believe this could become one of frequently asked questions, in my opinion it is best to add it for short span of ~2 to 4 months so users who don't update regularly will have chance to see it.

2020-07-01 23:18 UTC, micwoj92 commented on docs/next_steps/troubleshoot.md
> +One of [recent TF2 updates](https://www.teamfortress.com/post.php?id=62459) introduced new commands to disable chat. mastercomfig was updated shortly after to accomodate to this change. In the result
already fixed bro, saw that before you

2020-07-02 07:17 UTC, mastercoms requested changes

2020-07-02 07:17 UTC, mastercoms commented on docs/next_steps/troubleshoot.md
> +## Last update disabled my chat
Make this more generic: "My chat is disabled"

2020-07-02 07:39 UTC, micwoj92 commented on docs/next_steps/troubleshoot.md
> +## Last update disabled my chat
done

2020-07-02 08:00 UTC, mastercoms requested changes

2020-07-02 08:00 UTC, mastercoms commented on docs/next_steps/troubleshoot.md
> +One of [recent TF2 updates](https://www.teamfortress.com/post.php?id=62459) introduced new commands to disable chat. mastercomfig was updated shortly after to accommodate to this change. In the resul
```suggestion
[A TF2 update](https://www.teamfortress.com/post.php?id=62459) introduced the ability to completely disable text chat. mastercomfig was updated shortly after to accommodate this change, with the Very Low preset disabling chat completely. If you are using Very Low preset or the `messages=off` module, you can re-enable chat by adding `messages=on` to your `modules.cfg` file. To disable chat the old way you can use the `hud_saytext_time 0` command.
```

2020-07-02 08:05 UTC, micwoj92 commented on docs/next_steps/troubleshoot.md
> +One of [recent TF2 updates](https://www.teamfortress.com/post.php?id=62459) introduced new commands to disable chat. mastercomfig was updated shortly after to accommodate to this change. In the resul
Oh this is actually better. I was thinking only in scope of the recent update. And that it would be temporary.

2020-07-02 08:06 UTC, micwoj92 commented on docs/next_steps/troubleshoot.md
> +One of [recent TF2 updates](https://www.teamfortress.com/post.php?id=62459) introduced new commands to disable chat. mastercomfig was updated shortly after to accommodate to this change. In the resul
done

2020-07-02 08:07 UTC, mastercoms approved these changes

2020-07-02 08:08 UTC, merged