add most important tip
mastercoms/tf2cfg pull request #357
Opened 2020-07-07 10:54 UTC by micwoj92

2020-07-07 10:56 UTC, micwoj92 commented on docs/next_steps/troubleshoot.md
> +    Make sure that these are .cfg files and not .txt or .txt.cfg, you can enable file name extentions in windows 10 explorer and it will make any future configuration easier. To enable this, open the
done

2020-07-09 14:42 UTC, mastercoms requested changes

2020-07-09 14:42 UTC, mastercoms commented on docs/next_steps/troubleshoot.md
> +    Make sure that these are .cfg files and not .txt or .txt.cfg, you can enable file name extensions in windows 10 explorer and it will make any future configuration easier. To enable this, open the
```suggestion
    These should be `.cfg` files and not `.txt` or `.txt.cfg`. To ensure this, you can enable file name extensions in Windows and it will make any future configuration easier. Open the start menu, search for `Folder Options` and then select the first result. In the opened options window, go to the View tab, and under Advanced settings, uncheck Hide extensions for known file types. Finally, click ok.
```

2020-07-09 14:45 UTC, micwoj92 commented on docs/next_steps/troubleshoot.md
> +    Make sure that these are .cfg files and not .txt or .txt.cfg, you can enable file name extensions in windows 10 explorer and it will make any future configuration easier. To enable this, open the
done.

2020-07-09 14:49 UTC, mastercoms approved these changes

2020-07-09 14:49 UTC, merged