Make "cl_downloadfilter all" the default setting.
mastercoms/tf2cfg pull request #360
Opened 2020-07-08 02:17 UTC by xNanochip

This pull request makes the client cvar "cl_download filter all" the default module setting. The reason for this change is to eliminate the confusion on why clients get a giant "ERROR" for when they do not have required assets on a community server. This ensures that their game is running as intended and avoids obstructing game-play by not having the annoying "ERROR" sign.

2020-07-08 11:33 UTC, Leo40Git commented
The default should probably be `nosounds` if you're going for avoiding obstructive elements.

2020-07-08 11:37 UTC, micwoj92 commented
Keeping in line with the new approach to mastercomfig defaults, the default the downloads module should not be set.

2020-07-08 16:02 UTC, mastercoms requested changes

2020-07-08 16:02 UTC, mastercoms commented on config/mastercomfig/cfg/comfig/comfig.cfg
> +alias download download_all
```suggestion
alias download
```

2020-07-09 14:36 UTC, mastercoms requested changes
You should change the documented default in `modules.md`.

2020-07-10 06:11 UTC, xNanochip commented
I assume you mean modules.cfg?

2020-07-10 07:52 UTC, mastercoms commented
In addition to the diff you have in modules.cfg, every module has their default documented in modules.md. With the default change, modules.md needs to be updated.

2020-07-10 18:48 UTC, xNanochip commented
Okay, good to go?

2020-07-10 19:16 UTC, mastercoms approved these changes

2020-07-10 19:17 UTC, merged