Update packaging info in contributing.md
mastercoms/tf2cfg pull request #370
Opened 2020-07-12 23:43 UTC by micwoj92

Add basic info on needed tools
Remove github and discord mentions, as they are not needed to package.

2020-07-13 05:55 UTC, mastercoms requested changes
Those should not be removed, given that there should be documentation for future maintainers.

2020-07-13 09:14 UTC, micwoj92 commented
I only removed them from the contributing.md as they are not needed to package. Future maintainer should look in GitHub, because it is for developers. Removed info is still present in dev/README.md to which I plan rewrite/adding more info about all scripts present there in near future.

2020-07-13 10:39 UTC, mastercoms requested changes

2020-07-13 10:39 UTC, mastercoms commented on .github/CONTRIBUTING.md
> +* [VPC](https://developer.valvesoftware.com/wiki/VPK#Linux_.2F_Unix)
VPK

2020-07-13 12:30 UTC, micwoj92 commented on .github/CONTRIBUTING.md
> +* [VPC](https://developer.valvesoftware.com/wiki/VPK#Linux_.2F_Unix)
I copied that from dev/readme.md
I will make that change if you confirm that this needs to be "vpk" there. Thanks for pointing out.

2020-07-13 12:34 UTC, micwoj92 commented on .github/CONTRIBUTING.md
> +* [VPC](https://developer.valvesoftware.com/wiki/VPK#Linux_.2F_Unix)
I am mostly asking, because in #369 I updated link, but you did not mention it.

2020-07-13 12:35 UTC, micwoj92 commented on .github/CONTRIBUTING.md
> +* [VPC](https://developer.valvesoftware.com/wiki/VPK#Linux_.2F_Unix)
OH, I just saw it's "VDC" there. My mistake. Should be VDC or VPK then?

2020-07-13 12:46 UTC, mastercoms commented on .github/CONTRIBUTING.md
> +* [VPC](https://developer.valvesoftware.com/wiki/VPK#Linux_.2F_Unix)
VPK. There, it was suggesting to see the VDC (Valve Developer Community) for instructions on how to install the vpk tool. Now, it is part of a list of requirements, and thus the actual item being required and thus what should be written is VPK.

2020-07-13 13:55 UTC, micwoj92 commented on .github/CONTRIBUTING.md
> +* [VPC](https://developer.valvesoftware.com/wiki/VPK#Linux_.2F_Unix)
Done. I may have thought it means like Valve Development sCript? No idea how that came to my mind

2020-07-13 14:25 UTC, micwoj92 commented on docs/contributing.md
> +```
bro, this is draft, hold on

2020-07-13 14:32 UTC, micwoj92 commented
After thinking a bit about this  I came to conclusion that some might want to contribute to the release/announce scripts, so I added them in separate paragraph. Is this good @mastercoms ?

2020-07-15 05:35 UTC, mastercoms approved these changes

2020-07-15 05:43 UTC, merged