Add move_bind to docs, add Miscelaneous modules section
mastercoms/tf2cfg pull request #388
Opened 2020-09-03 02:02 UTC by treacherousfiend

-Logo and Mod Support have been moved to the new Miscelaneous modules section 
-Move bind added to this section as well
-Fix a missing period in custom configs part of docs

2020-09-04 21:44 UTC, mastercoms requested changes

2020-09-04 21:44 UTC, mastercoms commented on docs/customization/modules.md
> +Changes the keys that are used to move while the Null Movement addon is installed, if your preferred movement keys are not listed here, you can edit them manually outside of modules.cfg. Instructions
Can you move the instructions here?

2020-09-04 21:47 UTC, treacherousfiend commented on docs/customization/modules.md
> +Changes the keys that are used to move while the Null Movement addon is installed, if your preferred movement keys are not listed here, you can edit them manually outside of modules.cfg. Instructions
the instructions for manually making null move binds? sure, do you want me to remove it from its current place as well?

2020-09-04 21:49 UTC, mastercoms commented on docs/customization/modules.md
> +Changes the keys that are used to move while the Null Movement addon is installed, if your preferred movement keys are not listed here, you can edit them manually outside of modules.cfg. Instructions
Yeah just remove that whole section

2020-09-04 21:55 UTC, treacherousfiend commented on docs/customization/modules.md
> +Changes the keys that are used to move while the Null Movement addon is installed, if your preferred movement keys are not listed here, you can edit them manually outside of modules.cfg. Instructions
Might've gone a bit overkill with the "examples" section

2020-09-04 21:57 UTC, treacherousfiend commented on docs/customization/modules.md
> +Changes the keys that are used to move while the Null Movement addon is installed, if your preferred movement keys are not listed here, you can edit them manually outside of modules.cfg. Instructions
thinking about moving the manual editing section underneath the actual module, so as not to push the actual module down

2020-09-08 03:01 UTC, mastercoms approved these changes

2020-09-08 03:02 UTC, merged