Minor changes to the config
mastercoms/tf2cfg pull request #399
Opened 2020-10-05 06:14 UTC by Tiagoquix

2020-10-05 06:26 UTC, micwoj92 commented on docs/customization/modules.md
> +    If you do not have `user` folder you should create it. Same principle applies to the `autoexec.cfg` file.
above and below text is about modules, why change it then?

2020-10-05 06:27 UTC, mastercoms requested changes

2020-10-05 06:27 UTC, mastercoms commented on docs/customization/modules.md
> +    If you do not have `user` folder you should create it. Same principle applies to the `autoexec.cfg` file.
This is on the modules page. It's saying if you don't have modules.cfg, create it, just like if you don't have a user folder, create it.

2020-10-05 06:27 UTC, mastercoms commented on docs/customization/modules.md
> +### General Post-Processing
I do not agree that there should be a dash here.

2020-10-05 06:27 UTC, mastercoms commented on docs/customization/modules.md
> +Keep in mind that you must add your preferred `cl_detaildist` and `cl_detailfade` settings to your class configs if they are different from your preset, or else they will be overridden. You probably
Just remove this section, it's completely useless.

2020-10-05 06:27 UTC, mastercoms commented on docs/customization/modules.md
> +* **`download=auto`**: Whatever the user set in the game settings. By default, the game downloads every custom thing from community servers.
The game default is to download all custom files from the server.

2020-10-05 06:27 UTC, mastercoms commented on docs/customization/modules.md
> +Also known as linear interpolation (lerp or interp). Note: by default, mastercomfig sets this automatically per class, but setting it in your `modules.cfg` will override this behavior.
Remove this note, since it's covered in auto.

2020-10-05 06:27 UTC, mastercoms commented on docs/customization/modules.md
> +* **`snapshot_buffer=auto`**: Automatically sets the best interpolation value based on which class you are currently playing.
Automatically set per class.

2020-10-05 08:19 UTC, Tiagoquix commented on docs/customization/modules.md
> +* **`download=auto`**: Whatever the user set in the game settings. By default, the game downloads every custom thing from community servers.
Yes, that what I explained.

2020-10-05 08:19 UTC, Tiagoquix commented on docs/customization/modules.md
> +Keep in mind that you must add your preferred `cl_detaildist` and `cl_detailfade` settings to your class configs if they are different from your preset, or else they will be overridden. You probably
I Will remove it.

2020-10-05 08:21 UTC, Tiagoquix commented on docs/customization/modules.md
> +### General Post-Processing
You don't have to. The correct grammar is with a dash.

2020-10-08 19:21 UTC, Tiagoquix commented
I moved the `dynamic_background` module run to `finalize.cfg`. It's best to run it after everything has been set.

2020-10-08 19:24 UTC, Tiagoquix commented on docs/customization/modules.md
> +### General Post-Processing
@mastercoms https://english.stackexchange.com/questions/452969/pre-processing-post-processing-hyphen-presence-in-research-publications-writ

2020-10-09 01:41 UTC, mastercoms requested changes

2020-10-09 01:41 UTC, mastercoms commented on docs/customization/modules.md
> +* **`snapshot_buffer=auto`**: Automatically sets the best interpolation value per class.
Remove the note above: "Note: mastercomfig sets this automatically per class, but setting it in your `modules.cfg` will override this behavior."

2020-10-09 02:21 UTC, Tiagoquix commented
Done and done
@mastercoms @micwoj92

2020-10-09 02:52 UTC, mastercoms requested changes

2020-10-09 02:52 UTC, mastercoms commented on docs/faq.md
> +## Why is there no mastercomfig application?
Use app instead of application. The branding for mastercomfig 7 was always "app".

2020-10-09 04:14 UTC, Tiagoquix commented
Done @mastercoms

2020-10-15 18:45 UTC, mastercoms requested changes

2020-10-15 18:45 UTC, mastercoms commented on .github/ISSUE_TEMPLATE/bug_report.md
> +* Config version (don't say latest, say the actual version, found by running `version_comfig` in console):
```suggestion
* Config version: <!-- don't say latest, say the actual version, found by running `version_comfig` in console -->
```

2020-10-15 18:45 UTC, mastercoms commented on config/mastercomfig/cfg/comfig/comfig.cfg
> +alias snapshot_buffer_auto"alias snapshot_buffer"
I would rather use the shortcut for auto than a full module level.

2020-10-15 18:45 UTC, mastercoms commented on config/mastercomfig/cfg/comfig/comfig.cfg
> +alias download_auto"alias download"
I would rather use the shortcut for auto than a full module level.

2020-10-15 18:45 UTC, mastercoms commented on config/mastercomfig/cfg/comfig/comfig.cfg
> +alias sillygibs_auto"alias sillygibs"
I would rather use the shortcut for auto than a full module level.

2020-10-15 18:45 UTC, mastercoms commented on config/mastercomfig/cfg/comfig/comfig.cfg
> +alias ropes_off"r_drawropes 0;rope_rendersolid 0;r_ropetranslucent 0;rope_smooth 0;rope_subdiv 0;rope_collide 0;rope_wind_dist 0;rope_averagelight 0"
No benefit to setting 0. It has been intentionally removed from ropes.

2020-10-15 18:45 UTC, mastercoms commented on config/mastercomfig/cfg/comfig/comfig.cfg
> +//cl_crosshair_file "" // Style of crosshair
Space not needed

2020-10-15 18:45 UTC, mastercoms commented on config/mastercomfig/cfg/comfig/comfig.cfg
> +//ds_prefix "" // Prefix file names with this text
Space not needed

2020-10-15 18:45 UTC, mastercoms commented on config/templates/modules/modules.cfg
> +//jigglebones=force_on
Force on should not be default here.

2020-10-15 18:45 UTC, mastercoms commented on config/mastercomfig/cfg/comfig/finalize.cfg
> +dynamic_background // Run dynamic_background after everything
What is the actual benefit to this? Seems like nothing.

2020-10-15 18:49 UTC, Tiagoquix commented on .github/ISSUE_TEMPLATE/bug_report.md
> +* Config version (don't say latest, say the actual version, found by running `version_comfig` in console):
The idea is to make that so the user does not have to delete the warning sign to say his comfig version. I think it would be better like this:

* Config version<!-- don't say latest, say the actual version, found by running `version_comfig` in console -->:

2020-10-15 18:50 UTC, mastercoms commented on .github/ISSUE_TEMPLATE/bug_report.md
> +* Config version (don't say latest, say the actual version, found by running `version_comfig` in console):
I am fine with that

2020-10-15 18:51 UTC, Tiagoquix commented on config/mastercomfig/cfg/comfig/comfig.cfg
> +alias snapshot_buffer_auto"alias snapshot_buffer"
The ideia, along with download=auto and sillygibs=auto is that, if the user wants to enforce the module like other modules (textures=high being textures_high, for example), he can have this in his dispose.

2020-10-15 18:52 UTC, Tiagoquix commented on config/mastercomfig/cfg/comfig/comfig.cfg
> +alias ropes_off"r_drawropes 0;rope_rendersolid 0;r_ropetranslucent 0;rope_smooth 0;rope_subdiv 0;rope_collide 0;rope_wind_dist 0;rope_averagelight 0"
Alright, I'll revert this change.

2020-10-15 18:53 UTC, Tiagoquix commented on config/mastercomfig/cfg/comfig/comfig.cfg
> +//cl_crosshair_file "" // Style of crosshair
Are you sure? I think it is. Since if you use `cl_crosshair_filecrosshair3` it won't work since it will interpret the whole thing as a one cvar.

2020-10-15 18:53 UTC, Tiagoquix commented on config/mastercomfig/cfg/comfig/comfig.cfg
> +//ds_prefix "" // Prefix file names with this text
Are you sure? I think it is. Since if you use `ds_prefixSOMETHING` it won't work since it will interpret the whole thing as an one cvar.

2020-10-15 19:03 UTC, Tiagoquix commented on config/templates/modules/modules.cfg
> +//jigglebones=force_on
The `modules.cfg` file should follow a pattern.

By my analysis, I concluded that the values that are set by default in the comments are the values that are the higher value the module can have (by looking at the docs page, from below to above), or if they have a universal default (a default on almost all presets), they become the comment's default value. For instance, `bandwith` is `1.5Mbps` and not `8.0Mbps` that is the max value the module offers. But, `lighting` is `ultra`, and it is the max value the module have.

And, with this conclusion, I changed the `jigglebones` default module level to `force_on`.

2020-10-15 19:05 UTC, Tiagoquix commented on config/mastercomfig/cfg/comfig/finalize.cfg
> +dynamic_background // Run dynamic_background after everything
Mainly to avoid some problem that may occur. Also, I think that is best to run a `map_background` after everything has been set.

2020-10-15 19:16 UTC, Tiagoquix commented on .github/ISSUE_TEMPLATE/bug_report.md
> +* Config version (don't say latest, say the actual version, found by running `version_comfig` in console):
Done.

2020-10-15 19:18 UTC, Tiagoquix commented on config/mastercomfig/cfg/comfig/comfig.cfg
> +alias ropes_off"r_drawropes 0;rope_rendersolid 0;r_ropetranslucent 0;rope_smooth 0;rope_subdiv 0;rope_collide 0;rope_wind_dist 0;rope_averagelight 0"
Done.

2020-10-15 19:54 UTC, mastercoms commented on config/mastercomfig/cfg/comfig/comfig.cfg
> +//ds_prefix "" // Prefix file names with this text
quotes are interpreted as separate arguments.

2020-10-15 19:55 UTC, mastercoms commented on config/templates/modules/modules.cfg
> +//jigglebones=force_on
Except I'm telling you what my logic was for the defaults, and this should be on :)

2020-10-15 19:57 UTC, mastercoms commented on config/mastercomfig/cfg/comfig/comfig.cfg
> +alias snapshot_buffer_auto"alias snapshot_buffer"
I don't think that's really valuable, as that isn't the logic behind directly running a module level. Directly running a module level does not select a module, it applies the settings in that level. auto levels have no settings to apply, thus they would be blank.

2020-10-15 19:57 UTC, mastercoms commented on config/mastercomfig/cfg/comfig/comfig.cfg
> +//cl_crosshair_file "" // Style of crosshair
quotes are interpreted as separate arguments.

2020-10-15 20:00 UTC, Tiagoquix commented on config/templates/modules/modules.cfg
> +//jigglebones=force_on
Nice answer. You looked like a queen giving me orders now. I will revert this change.

2020-10-15 20:02 UTC, Tiagoquix commented on config/mastercomfig/cfg/comfig/comfig.cfg
> +//ds_prefix "" // Prefix file names with this text
Done.

2020-10-15 20:02 UTC, Tiagoquix commented on config/mastercomfig/cfg/comfig/comfig.cfg
> +//cl_crosshair_file "" // Style of crosshair
Done.

2020-10-15 20:03 UTC, Tiagoquix commented on config/templates/modules/modules.cfg
> +//jigglebones=force_on
Done.

2020-10-15 20:06 UTC, Tiagoquix commented on config/mastercomfig/cfg/comfig/comfig.cfg
> +alias snapshot_buffer_auto"alias snapshot_buffer"
I understood you point of view, but I don't think you understood mine.
For example, if an user uses `sillygibs_on` in the console, he only can revert the change to `sillygibs=auto` if him uses `sillygibs=auto;run_modules` since `sillygibs_auto` doesn't exist.

2020-10-15 20:08 UTC, micwoj92 commented on config/mastercomfig/cfg/comfig/comfig.cfg
> +alias snapshot_buffer_auto"alias snapshot_buffer"
but like the point of auto is to not change what people set, so your argument here makes no sense.

2020-10-15 20:09 UTC, mastercoms commented on config/mastercomfig/cfg/comfig/comfig.cfg
> +alias snapshot_buffer_auto"alias snapshot_buffer"
Your implementation would also require a run_modules.

2020-10-15 20:17 UTC, Tiagoquix commented on config/mastercomfig/cfg/comfig/comfig.cfg
> +alias snapshot_buffer_auto"alias snapshot_buffer"
@micwoj92 "but like the point of auto is to not change what people set, so your argument here makes no sense."
The point of `auto` level is to let the config change the values, not to let the user change them. The only exception is the `download` module.

@mastercoms No, it won't.
For example: if a user has `snapshot_buffer=safe` in his `modules.cfg` and then he executes `snapshot_buffer_auto` into the console, it won't require a `run_modules`, since the function of `snapshot_buffer_auto` will act like the user is using `snapshot_buffer=auto`.

2020-10-15 20:19 UTC, mastercoms commented on config/mastercomfig/cfg/comfig/comfig.cfg
> +alias snapshot_buffer_auto"alias snapshot_buffer"
`snapshot_buffer=auto` previously had the same exact content as you have now for `snapshot_buffer_auto`, what are you talking about?

2020-10-15 20:22 UTC, mastercoms commented on config/mastercomfig/cfg/comfig/comfig.cfg
> +alias snapshot_buffer_auto"alias snapshot_buffer"
Disregarding what is the same, all you are doing here in your new changes is making `snapshot_buffer=auto` set the snapshot buffer module to set snapshot buffer to auto, which is just a horribly convoluted set up which doesn't act like any other module.

2020-10-15 20:24 UTC, Tiagoquix commented on config/mastercomfig/cfg/comfig/comfig.cfg
> +alias snapshot_buffer_auto"alias snapshot_buffer"
@mastercoms Yes but, following the config pattern, user's won't think that `snapshoft_buffer=auto` can be used the same way as `snapshoft_buffer_auto`. For example, you can use `lighting=ultra` but you will need `run_modules` for that, and by using `lighting_ultra` you don't need to run modules.

At least, might I alias `snapshot_buffer_auto` to `snapshoft_buffer=auto` to it be like a shortcut?

2020-10-15 20:24 UTC, mastercoms commented on config/mastercomfig/cfg/comfig/comfig.cfg
> +alias snapshot_buffer_auto"alias snapshot_buffer"
**Your changes**

` alias snapshot_buffer_auto"alias snapshot_buffer" `

`snapshot_buffer_auto` sets `snapshot_buffer` to empty (auto state).

`alias snapshot_buffer=auto"alias snapshot_buffer snapshot_buffer_auto"`

`snapshot_buffer=auto` sets `snapshot_buffer` to `snapshot_buffer_auto`, which sets `snapshot_buffer` to auto state. Therefore, on the actual run of this module, you are only simply making it then clear itself on a second run. This does not work, and means the module level has two useless states depending on how many times modules are run.

2020-10-15 20:25 UTC, mastercoms commented on config/mastercomfig/cfg/comfig/comfig.cfg
> +alias snapshot_buffer_auto"alias snapshot_buffer"
**Original**

`alias snapshot_buffer=auto"alias snapshot_buffer"`

`snapshot_buffer=auto` sets `snapshot_buffer` to empty (auto state).

2020-10-15 20:26 UTC, Tiagoquix commented on config/mastercomfig/cfg/comfig/comfig.cfg
> +alias snapshot_buffer_auto"alias snapshot_buffer"
Alright, I'll revert these changes but I'll alias `snapshoft_buffer_auto` to ``snapshot_buffer=auto` to be a shortcut.
Like I said, the config follows a pattern.

2020-10-15 20:27 UTC, mastercoms commented on config/mastercomfig/cfg/comfig/comfig.cfg
> +alias snapshot_buffer_auto"alias snapshot_buffer"
And finally, if you look at _any other module_, you will see that the actual level command never interacts with the module. It only applies the game settings. This is just how modules are organized.

For example, `packet_rate_big`, it sets a few cvars involving max routable, compression, etc. It does not do anything with the packet_rate module itself.

2020-10-15 20:28 UTC, mastercoms commented on config/mastercomfig/cfg/comfig/comfig.cfg
> +alias snapshot_buffer_auto"alias snapshot_buffer"
No, do not do this. It creates a module level which is unlike anything else, and creates states within the config which are either useless or harmful. `snapshot_buffer_auto` should _only_ apply the settings which are associated with an `auto` level, i.e. **nothing**.

2020-10-15 20:32 UTC, Tiagoquix commented on config/mastercomfig/cfg/comfig/comfig.cfg
> +alias snapshot_buffer_auto"alias snapshot_buffer"
Done.

2020-10-15 20:43 UTC, mastercoms approved these changes

2020-10-15 20:43 UTC, merged