Added Nvidia Control Panel Settings
mastercoms/tf2cfg pull request #423
Opened 2020-12-12 20:15 UTC by Sirbucket

A great guide on Nvidia control panel settings added, many of the settings are shared with Radeon so the guide can be used for AMD GPUs as well.

2020-12-15 04:18 UTC, mastercoms requested changes

2020-12-15 04:18 UTC, mastercoms commented on docs/os/windows.md
> +## Disabling Nahimic
Nahimic is an overlay, so it should be listed under disable overlays.

2020-12-15 04:18 UTC, mastercoms commented on docs/os/windows.md
> +[Nvidia Control Panel Optimization](https://www.youtube.com/watch?v=ugadZ86uTik) Does an excellent job explaining how to configure the Nvidia control panel and goes over each setting in depth and why
This is meant to be a text guide, with additional sources for users to expand on the reasoning behind a recommendation or to better understand it. It shouldn't be a way to list a bunch of other tutorials, especially YouTube videos.

2020-12-20 07:07 UTC, Sirbucket commented on docs/os/windows.md
> +[Nvidia Control Panel Optimization](https://www.youtube.com/watch?v=ugadZ86uTik) Does an excellent job explaining how to configure the Nvidia control panel and goes over each setting in depth and why
Ahh understood, did you see my one on power though (It has a tutorial video but I can remove that one if you don't want and I can summarize all the settings into text for this part.)

2020-12-20 07:08 UTC, Sirbucket commented on docs/os/windows.md
> +## Disabling Nahimic
I did that so it fit in uniform with the other ones, all the others had 2 ## so I thought 3 looked weird.

2020-12-20 07:11 UTC, Sirbucket commented on docs/os/windows.md
> +[Nvidia Control Panel Optimization](https://www.youtube.com/watch?v=ugadZ86uTik) Does an excellent job explaining how to configure the Nvidia control panel and goes over each setting in depth and why
Saw what you said, a OK, I'll rework this though to remove the tutorial like format from youtube videos and make a simple google doc detailing optimal settings for performance, middle ground, and visuals

2020-12-20 07:30 UTC, micwoj92 commented on docs/os/windows.md
> +[Nvidia Control Panel Optimization](https://www.youtube.com/watch?v=ugadZ86uTik) Does an excellent job explaining how to configure the Nvidia control panel and goes over each setting in depth and why
why google doc?

2020-12-20 08:51 UTC, Sirbucket reviewed
Also I do understand that both of those videos are pretty offensive so I completely get why you wouldn't want that in there anyways, I just liked them because the dude took time to look into the settings.

2020-12-20 08:51 UTC, Sirbucket commented on docs/os/windows.md
> +## Disabling Nahimic
Is the third # supposed to mean it's a new section then?

2020-12-20 08:51 UTC, Sirbucket commented on docs/os/windows.md
> +[Nvidia Control Panel Optimization](https://www.youtube.com/watch?v=ugadZ86uTik) Does an excellent job explaining how to configure the Nvidia control panel and goes over each setting in depth and why
It's simple to put it in there and put in a link, I can just figure out how to upload a text file link to github if that's what you want me to do?

2020-12-20 08:51 UTC, Sirbucket commented on docs/os/windows.md
> +[Nvidia Control Panel Optimization](https://www.youtube.com/watch?v=ugadZ86uTik) Does an excellent job explaining how to configure the Nvidia control panel and goes over each setting in depth and why
If you don't like the specific settings lists I can delete those and just have the details document

2020-12-20 08:57 UTC, micwoj92 commented on docs/os/windows.md
> +[Nvidia Control Panel Optimization](https://www.youtube.com/watch?v=ugadZ86uTik) Does an excellent job explaining how to configure the Nvidia control panel and goes over each setting in depth and why
Why do link to google docs when this is mastercomfig **docs**?

2020-12-21 22:43 UTC, Sirbucket commented on docs/os/windows.md
> +[Nvidia Control Panel Optimization](https://www.youtube.com/watch?v=ugadZ86uTik) Does an excellent job explaining how to configure the Nvidia control panel and goes over each setting in depth and why
I thought it'd be too cluttered, you'd need to add an entirely seperate section if you wanted me to include it in the mastercomfigs doc as a standalone.

2020-12-21 22:47 UTC, Sirbucket commented on docs/os/windows.md
> +[Nvidia Control Panel Optimization](https://www.youtube.com/watch?v=ugadZ86uTik) Does an excellent job explaining how to configure the Nvidia control panel and goes over each setting in depth and why
Well I mean I could do it myself but it'd be a stretch to add, easier to just shrink it down into 4 links

2020-12-22 19:33 UTC, mastercoms commented on docs/os/windows.md
> +## Disabling Nahimic
Yes the third means it is a 3rd level header, thereby making a section under the 2nd level header above.

2020-12-22 19:34 UTC, mastercoms requested changes

2020-12-22 19:34 UTC, mastercoms commented on docs/os/windows.md
> +[DESCRIPTION](https://docs.google.com/document/d/1-k14uBdWv3RDIfdfvR6ICCA9wYgUYjflgd-NJkIFIiI/edit?usp=sharing): Describes each setting in a general overview
External links are not allowed in this fashion. Such a list of customizations should be tracked and reviewed in the docs.

2020-12-23 03:52 UTC, Sirbucket commented on docs/os/windows.md
> +[DESCRIPTION](https://docs.google.com/document/d/1-k14uBdWv3RDIfdfvR6ICCA9wYgUYjflgd-NJkIFIiI/edit?usp=sharing): Describes each setting in a general overview
Got it, I'll figure out a way to put it in without cluttering the page and I'll remove the change to the #

2021-01-07 12:33 UTC, Tiagoquix requested changes

2021-01-07 12:33 UTC, Tiagoquix commented on docs/os/windows.md
> +## Enable Hardware-accelerated GPU Scheduling
Since you are capitalizing the titles, I think you should put the letter A from "accelerated" as a capital letter as well.

2021-03-12 19:16 UTC, mastercoms commented
Closing due to inactivity.

2021-03-12 19:16 UTC, closed without merging