Docs changes
mastercoms/tf2cfg pull request #430
Opened 2020-12-31 03:29 UTC by Tiagoquix

The changes that I made are just perfectionist changes. I just changed a text here and there.

Two changes I would like to highlight are:

- I removed the suggestions for disabling Game Mode and Full Screen Optimizations. Windows 10 has evolved over time and these changes are no longer strictly necessary. So much so that new games, such as Shadow of the Tomb Raider and Hitman 2 already feature a new full screen mode called Exclusive Full Screen, in which it was made exclusively to benefit from these Windows 10 changes.

- The removal of the "No lightwarps" lines from the medium and medium_high levels of the lighting module. These changes were made based on this commit: https://github.com/mastercomfig/mastercomfig/commit/f7ba3c450457ee7a018f0658bc226e9bc50412bd

2020-12-31 03:32 UTC, Tiagoquix commented
Yes, I know that changes related to the docs should be targeted to the release branch, but I submitted the changes to the develop branch on purpose. I don't want them to go on the air right now.

2021-01-22 19:08 UTC, mastercoms requested changes
Please revert your changes to the launch options format, the preset and addons format, the removal of Windows tweaks, remove periods from see also.

2021-01-22 19:08 UTC, mastercoms commented on docs/tf2/misconceptions.md
> +* `rate 60000` : This is lower than the TF2 default rate of `80000`. TF2 default network settings are already on the low-end. Why would you set rate lower, especially when you're increasing packet ra
This should remain a comma separated list. It is not a command, it is a structure within normal grammar describing two entities which increase packet rates.

2021-01-25 00:25 UTC, Tiagoquix commented
> Please revert your changes to the launch options format, the preset and addons format, the removal of Windows tweaks, remove periods from see also.

Done. I also corrected the description for the shadows module in the docs.

2021-01-29 15:17 UTC, mastercoms approved these changes

2021-01-29 15:17 UTC, merged