Add Medium-Low gibs module
mastercoms/tf2cfg pull request #449
Opened 2021-02-05 21:49 UTC by treacherousfiend

As pointed out by someone in our discord, the low module for gibs limits them to 2 pieces per object, and medium doesn't limit them at all. A quick check ingame shows that an exploding player can spawn anywhere between 9-12 gibs based on the class.

This Medium-Low module attempts to create a sweet spot between the two modules by limiting gibs to 4 per object.

The value of 4 gibs per object has little basis, and other values may fit better.

PR includes new module and it addition to the docs.

2021-02-05 22:10 UTC, micwoj92 commented
also needs changes data/modules.json

2021-02-07 12:13 UTC, Tiagoquix commented
Hello. Please remove the spaces from ``alias gibs_medium_low"cl_burninggibs 0; props_break_max_pieces 4; tf_playergib 1;sillygibs_off;sillygibs"``, and also, update your [modules.cfg file](https://github.com/treacherousfiend/mastercomfig/blob/medium_low_gibs/config/templates/modules/modules.cfg) (the template file).

Remember that your change will not force this new level of the gibs module to be automatically enabled for everyone in some preset. You would have to change some preset (like the medium-high), but I do not suggest you to. This is just a reminder.

2021-02-07 18:24 UTC, mastercoms requested changes
Add to modules template

2021-02-07 20:50 UTC, treacherousfiend commented
fixed

2021-02-07 20:53 UTC, mastercoms approved these changes

2021-02-07 20:53 UTC, merged