Changed debug_output to toggle developer cvar
mastercoms/tf2cfg pull request #510
Opened 2021-06-13 18:08 UTC by TheDIGS

Tiny PR but it's my first so fuck it.

All this changes is the `debug_output` command which currently sets `developer` to 1.

This changes that to toggle it instead, so running `debug_output` twice would toggle it from 0 to 1 to 0 etc.

2021-06-13 18:11 UTC, micwoj92 commented
"Tiny PR but it's my first so fuck it."

You don't know what a tiny pr is, bro.

2021-06-13 18:17 UTC, mastercoms requested changes

2021-06-13 18:17 UTC, mastercoms commented on config/mastercomfig/cfg/comfig/comfig.cfg
> +alias debug_output"incrementvar developer 0 1 1"
This can use `toggle developer` instead. But we can also use `incrementvar developer 0 4 1` since that will cycle through all available levels.

2021-06-13 18:21 UTC, TheDIGS commented on config/mastercomfig/cfg/comfig/comfig.cfg
> +alias debug_output"incrementvar developer 0 1 1"
are there more levels than 0-1?

2021-06-13 18:22 UTC, mastercoms commented on config/mastercomfig/cfg/comfig/comfig.cfg
> +alias debug_output"incrementvar developer 0 1 1"
Yes, it goes up to 4.

2021-06-13 18:25 UTC, TheDIGS commented on config/mastercomfig/cfg/comfig/comfig.cfg
> +alias debug_output"incrementvar developer 0 1 1"
Can I edit the PR or something? I'm kinda new to GH.

2021-06-13 18:26 UTC, micwoj92 commented on config/mastercomfig/cfg/comfig/comfig.cfg
> +alias debug_output"incrementvar developer 0 1 1"
Yes, edit your branch

2021-06-13 18:33 UTC, TheDIGS commented on config/mastercomfig/cfg/comfig/comfig.cfg
> +alias debug_output"incrementvar developer 0 1 1"
Ok gonna do this in a minute

2021-06-13 18:52 UTC, TheDIGS commented
There are now multiple commands:
`debug_output` = `developer 1`
`debug_output_toggle` = run through all modes
`debug_output_<x>` = specific mode

2021-06-13 20:59 UTC, Tiagoquix requested changes
See the comment below.

2021-06-13 20:59 UTC, Tiagoquix commented on config/mastercomfig/cfg/comfig/comfig.cfg
> +alias debug_output_toggle"incrementvar developer 0 4 1"
Only `debug_output"incrementvar developer 0 4 1"` would be sufficient.
The other aliases are kind of unnecessary.

2021-06-14 15:56 UTC, TheDIGS commented on config/mastercomfig/cfg/comfig/comfig.cfg
> +alias debug_output_toggle"incrementvar developer 0 4 1"
I don't think many people really want 3 and 4 anyway, so my reasoning is that more choice is better than more simplicity.

2021-06-14 19:57 UTC, Tiagoquix commented on config/mastercomfig/cfg/comfig/comfig.cfg
> +alias debug_output_toggle"incrementvar developer 0 4 1"
I disagree. I believe very few people actually use debug commands, so I don't think we should have that many commands. Anyway, it's up to you to decide on the final model and mastercoms will either reject or approve, but I prefer fewer commands.

2021-06-14 21:00 UTC, mastercoms commented on config/mastercomfig/cfg/comfig/comfig.cfg
> +alias debug_output_toggle"incrementvar developer 0 4 1"
I am fine with digs' solution.

2021-06-14 21:02 UTC, mastercoms approved these changes

2021-06-14 21:02 UTC, merged

2021-06-14 23:50 UTC, Tiagoquix commented
The docs should be changed too @mastercoms @TheDIGS

2021-06-15 02:01 UTC, treacherousfiend commented
Although this PR has already been merged, I think we should do some more research. The wiki states that there are 4 values for `developer`, but i can't get any more or less info to show up on `developer` 3 and 4. I also couldn't find references in the code to 3 or 4, but i might've missed it.

It's also worth pointing out that although its not mentioned on the wiki, TF2 (and potentially other source games) has `developer -1`, which outputs to the top left corner without adding anymore to the actual console output.

2021-06-15 02:32 UTC, mastercoms commented
Yeah that's right, 3 and 4 are unused in the current build.