Add new debug commands to docs
mastercoms/tf2cfg pull request #512
Opened 2021-06-15 01:54 UTC by treacherousfiend

Add commands added by #510 to docs. This PR probably needs some adjustments, but its a good baseline.

2021-06-15 02:37 UTC, Tiagoquix commented
https://github.com/treacherousfiend/mastercomfig/pull/5

@treacherousfiend

2021-06-15 02:38 UTC, micwoj92 commented
@treacherousfiend

2021-06-15 02:52 UTC, Tiagoquix commented
@treacherousfiend https://github.com/mastercomfig/mastercomfig/commit/42cde266ad89e337572c0dabfbf11b9c62b6ddac

debug_output_display should be added to the docs

2021-06-15 03:29 UTC, Tiagoquix requested changes

2021-06-15 03:29 UTC, Tiagoquix commented on docs/customization/custom_configs.md
> +* `debug_output_display`: Display console output in the corner of the screen without adding additional information.
@treacherousfiend replace "adding" with "showing" or remove it

"adding additional information" is weird

2021-06-16 12:09 UTC, mastercoms approved these changes

2021-06-16 12:09 UTC, merged