Update troubleshoot.md
mastercoms/tf2cfg pull request #513
Opened 2021-06-15 13:42 UTC by Tiagoquix

2021-06-15 13:54 UTC, hipocentrum commented on docs/next_steps/troubleshoot.md
> +lighting=medium
I do not agree with that change. Lighting modules do much more than that and it can cause more performance impact for people that already opted for option that gives as much fps as possible.

2021-06-16 12:12 UTC, mastercoms requested changes

2021-06-16 12:12 UTC, mastercoms commented on config/mastercomfig/cfg/comfig/mm_override.cfg
> +cl_ragdoll_fade_time 15
This is not needed

2021-06-16 12:12 UTC, mastercoms commented on docs/next_steps/troubleshoot.md
> +>Most Valve games have a built-in command for monitoring your CPU speed. If you add "+cpu_frequency_monitoring 2" to your launch options then the CPU's speed will be measured every two seconds. The m
This seems like a mistaken change.

2021-06-16 12:12 UTC, mastercoms commented on docs/next_steps/troubleshoot.md
> +## Item panels aren't loading
This should be changed in an independent PR. Everything else can be added to the current release docs.

2021-06-16 12:12 UTC, mastercoms commented on config/mastercomfig/cfg/comfig/comfig.cfg
> -alias ragdolls_low ragdolls_off
Do not send PRs for deprecated removals.

2021-06-16 14:29 UTC, Tiagoquix commented on docs/next_steps/troubleshoot.md
> +>Most Valve games have a built-in command for monitoring your CPU speed. If you add "+cpu_frequency_monitoring 2" to your launch options then the CPU's speed will be measured every two seconds. The m
No, I just removed the space between ">" and "Most" in the start and added a comma after "`overheat)`" (it is right at the end).

2021-06-16 14:30 UTC, mastercoms commented on docs/next_steps/troubleshoot.md
> +>Most Valve games have a built-in command for monitoring your CPU speed. If you add "+cpu_frequency_monitoring 2" to your launch options then the CPU's speed will be measured every two seconds. The m
Why would you remove the space? And the comma, while technically correct, is not necessary since the parentheses gives appropriate amount of flow separation.

2021-06-16 14:31 UTC, Tiagoquix commented on docs/next_steps/troubleshoot.md
> +## Item panels aren't loading
I prefer to stick with the develop branch this time because there are more changes. No need to update the docs right now.

2021-06-16 14:33 UTC, mastercoms commented on docs/next_steps/troubleshoot.md
> +## Item panels aren't loading
There won't be a release for a while. Please do these changes separately, or this PR will not be accepted.

2021-06-16 14:33 UTC, Tiagoquix commented on docs/next_steps/troubleshoot.md
> +>Most Valve games have a built-in command for monitoring your CPU speed. If you add "+cpu_frequency_monitoring 2" to your launch options then the CPU's speed will be measured every two seconds. The m
> Why would you remove the space?

Because of Sider bot. I will revert this change.

2021-06-16 14:33 UTC, mastercoms commented on docs/next_steps/troubleshoot.md
> +>Most Valve games have a built-in command for monitoring your CPU speed. If you add "+cpu_frequency_monitoring 2" to your launch options then the CPU's speed will be measured every two seconds. The m
Ok, then I misunderstood the requirements. You can keep this change.

2021-06-19 11:47 UTC, closed without merging

2021-06-19 11:55 UTC, Tiagoquix commented
Moved to #518

2021-06-19 11:56 UTC, Tiagoquix commented
@mastercoms