Update define_langs.cfg
mastercoms/tf2cfg pull request #534
Opened 2021-06-27 07:09 UTC by BlenderAddict

polish definition

2021-06-27 15:06 UTC, micwoj92 requested changes

2021-06-27 15:06 UTC, micwoj92 commented on config/mastercomfig/cfg/lang/pl.cfg
> +alias null_movement_echo"echo Załadowano moduł 'Anty-Anulowania Ruchu'"
Ja tu bym dal angielska nazwe

2021-06-27 15:06 UTC, micwoj92 commented on config/mastercomfig/cfg/lang/pl.cfg
> +alias transparent_vm_echo"echo Załadowano moduł przezroczystych Modeli Widoku"
Tu raczej powinno byc modeli broni. Najlepiej sprawdzic, jak w tf2 jest tlumaczone, zeby bylo zgodne z oficjalnym tlumaczeniem.

2021-06-27 15:06 UTC, micwoj92 commented on config/mastercomfig/cfg/lang/pl.cfg
> +alias block_antialias_echo"echo Ta komenda jest zablokowana aby zapobiec przeładowaniu systemu materiałów. Jeżeli chcesz to zmienić, użyj modułu Anty-Aliasingu."
Przecinek przed aby

2021-06-27 15:08 UTC, micwoj92 commented
Latwo krytykowac, ale nie tlumaczysz konsekwentnie, jezeli Nazwy Wszystkich Modulow Piszesz W Ten Sposob, to czego tam nagle jest "Załadowano moduł wyłączający tutorial"? Zamiast np. Zaladowano modul Wylaczania Tutorialu. Oczywiscie z polskimi znakami diaktrycznymi.

2021-06-27 15:30 UTC, BlenderAddict commented on config/mastercomfig/cfg/lang/pl.cfg
> +alias null_movement_echo"echo Załadowano moduł 'Anty-Anulowania Ruchu'"
o którą linie ci dokładnie chodzi?

2021-06-27 16:00 UTC, BlenderAddict commented on config/mastercomfig/cfg/lang/pl.cfg
> +alias transparent_vm_echo"echo Załadowano moduł przezroczystych Modeli Widoku"
masz racje, poprawiłem to na to jak było przetłumaczone w tf2

2021-06-27 16:15 UTC, micwoj92 commented on config/mastercomfig/cfg/lang/pl.cfg
> +alias null_movement_echo"echo Załadowano moduł 'Anty-Anulowania Ruchu'"
O ta gdzie skomentowalem, 5

2021-07-04 23:14 UTC, micwoj92 commented
@mastercoms will this get merged?

2021-07-04 23:36 UTC, mastercoms commented
I was waiting for your approval

2021-07-05 00:25 UTC, micwoj92 requested changes
That's only changes needed, otherwise it looks good. I thought that it's not added because the docs don't support polish.

2021-07-05 00:25 UTC, micwoj92 commented on config/mastercomfig/cfg/lang/pl.cfg
> +alias mm_override_echo"echo Zmieniono ustawienia mastercomfig do użytku w Matchmakingu Kompetetytorskim"
Here instead of "Matchmakingu Kompetetytorskim" it should say "Trybie rankingowym" as it's official translation
I have no idea how do you even come out with Kompetetytorskim

https://wiki.teamfortress.com/wiki/Competitive_Mode/pl

2021-07-05 00:25 UTC, micwoj92 commented on config/mastercomfig/cfg/lang/pl.cfg
> +alias block_antialias_echo"echo Ta komenda jest zablokowana aby zapobiec przeładowaniu systemu materiałów. Jeżeli chcesz to zmienić, użyj modułu Anty-Aliasingu."
And here it needs comma before the word "aby"

2021-07-05 01:47 UTC, micwoj92 commented on config/mastercomfig/cfg/lang/pl.cfg
> +alias block_antialias_echo"echo Ta komenda jest zablokowana aby zapobiec przeładowaniu systemu materiałów. Jeżeli chcesz to zmienić, użyj modułu Anty-Aliasingu."
```suggestion
alias block_antialias_echo"echo Ta komenda jest zablokowana, aby zapobiec przeładowaniu systemu materiałów. Jeżeli chcesz to zmienić, użyj modułu Anty-Aliasingu."
```

2021-07-05 01:47 UTC, micwoj92 commented on config/mastercomfig/cfg/lang/pl.cfg
> +alias block_antialias_echo"echo Ta komenda jest zablokowana aby zapobiec przeładowaniu systemu materiałów. Jeżeli chcesz to zmienić, użyj modułu Anty-Aliasingu."
ok, I found out how to make suggestions lol

2021-07-05 01:47 UTC, micwoj92 commented on config/mastercomfig/cfg/lang/pl.cfg
> +alias mm_override_echo"echo Zmieniono ustawienia mastercomfig do użytku w Matchmakingu Kompetetytorskim"
```suggestion
alias mm_override_echo"echo Zmieniono ustawienia mastercomfig do użytku w Trybie rankingowym"
```

2021-07-08 19:21 UTC, micwoj92 commented
@BlenderAddict

2021-07-15 01:13 UTC, mastercoms approved these changes

2021-07-15 01:13 UTC, merged