Integrate better bot support into mastercomfig. (#558)
mastercoms/tf2cfg pull request #562
Opened 2021-07-18 12:51 UTC by WhyIsEvery4thYearAlwaysBad

For #558. PR shouldn't be closed until it's ready to merge, unless if the maintainer rejects it.

* I decided to exec the `bot_skill` module in `game.cfg`, as having it in `game_overrides.cfg` would just have made redundant console output. Check the comments in `game.cfg` for more information. 

* I ended up having to execute the `tf_bot*` cvars in a file, because every time I tried to run them all in an alias, it would cause a buffer overflow.

* Seems like `mp_highlander 1` only causes problems for bots when adding bots *after* it's been set. Adding bots before setting `mp_highlander 1` seems to cause no problems and functions as usual.

* I'm not really sure how I should model the `tf_bot*` cvars and `bot_skill` module. Maybe base them off playtime in hours, or the knowledge of a typical player?

* The current `tf_bot` cvars haven't been tested thoroughly yet as this is just the initial setup for bot support.

2021-07-19 00:43 UTC, WhyIsEvery4thYearAlwaysBad commented
The PR is ready for review now.

2021-07-22 11:12 UTC, micwoj92 commented
> The PR is ready for review now.

You said that yet you keep adding more and more changes. It only makes reviewing harder.

2021-07-23 06:40 UTC, WhyIsEvery4thYearAlwaysBad commented
> > The PR is ready for review now.
> 
> You said that, yet you keep adding more and more changes. It only makes reviewing harder.

Right sorry. I thought I had finished up everything, but then realized there were bugs I had to patch.

2021-07-29 20:53 UTC, mastercoms requested changes
Could you refactor this into an addon?

2021-07-30 09:58 UTC, WhyIsEvery4thYearAlwaysBad commented
Yes I can refactor this change into an addon.

2021-07-30 20:02 UTC, WhyIsEvery4thYearAlwaysBad commented
Finished converting the changes into an addon. @mastercoms

2021-09-09 13:39 UTC, micwoj92 commented on docs/customization/modules.md
> -* **`bot_skill=expert`**: Applies expert difficulty and optimizations to bots.
This is only confusing.

2021-09-10 08:13 UTC, WhyIsEvery4thYearAlwaysBad commented on docs/customization/modules.md
> -* **`bot_skill=expert`**: Applies expert difficulty and optimizations to bots.
Yeah. Looking at the modules documentation again, the explanations seem confusing.

2021-09-18 03:54 UTC, WhyIsEvery4thYearAlwaysBad commented
@mastercoms All 3 checks have passed. I'm currently waiting for your approval.

2021-09-19 16:29 UTC, mastercoms commented
There are merge conflicts

2021-09-20 01:48 UTC, WhyIsEvery4thYearAlwaysBad commented
@mastercoms I fixed merge conflicts.

2021-09-20 09:32 UTC, Tiagoquix commented
Thanks for your addon suggestion, but based on my review, this addon is too complex for for a very small effect/gain. In the end, few people would use it due to the amount of commands and so on.

Even so, I suggest you to do not give up and upload it to GameBanana.

2021-09-20 09:32 UTC, closed without merging

2021-09-20 11:55 UTC, WhyIsEvery4thYearAlwaysBad commented
I agree; this addon feels too convoluted for mastercomfig. I have setup [a gitlab repo with the bot-support addon](https://gitlab.freedesktop.org/WhyIsEvery4thYearAlwaysBad/mastercomfig-bot-support/-/tree/develop/) if anyone needs it though.