Add Scottish Resistance sticky outline fix
mastercoms/tf2cfg pull request #569
Opened 2021-08-06 05:20 UTC by treacherousfiend

Its a relatively common question, and considering it can be fixed with modules I feel like it should be mentioned either here or on the modules page.

2021-08-06 08:03 UTC, Tiagoquix commented
Does this fix work for DX8 users?

2021-08-06 08:09 UTC, treacherousfiend commented
I had no clue there were even issues with the SR on DX8, i'll have to do some testing

2021-08-16 01:07 UTC, mastercoms requested changes

2021-08-16 01:07 UTC, mastercoms commented on docs/next_steps/quick_fixes.md
> +Due to a bug in the game, the outlines for Scottish Resistance stickybombs only appears when objective outlines are enabled. You can fix this by adding `outlines=medium` to your `modules.cfg`.
It's not a bug, `glow_outline_effect_enable` controls all outline effects. I would just say that SR stickies require outlines, which can be enabled with at least outlines=medium module level.

2021-08-16 01:21 UTC, treacherousfiend commented on docs/next_steps/quick_fixes.md
> +Due to a bug in the game, the outlines for Scottish Resistance stickybombs only appears when objective outlines are enabled. You can fix this by adding `outlines=medium` to your `modules.cfg`.
Should be better now? i'll let you resolve if you think its good

2021-08-16 01:22 UTC, Tiagoquix commented on docs/next_steps/quick_fixes.md
> +Due to a bug in the game, the outlines for Scottish Resistance stickybombs only appears when objective outlines are enabled. You can fix this by adding `outlines=medium` to your `modules.cfg`.
So this won't work on DirectX 8.

@treacherousfiend Please add a note about this.

2021-09-10 03:11 UTC, mastercoms requested changes

2021-09-10 03:11 UTC, mastercoms commented on docs/next_steps/quick_fixes.md
> +On some Mastercomfig presets, outlines are disabled. The outline settings include player and objective outlines as well as outlines for Scottish Resistance stickybombs. You can enable outlines by add
```suggestion
On some mastercomfig presets, outlines are disabled. The outline settings include player and objective outlines as well as outlines for Scottish Resistance stickybombs. You can enable outlines by adding `outlines=medium` (or higher) to your `modules.cfg`.
```

2021-09-10 03:11 UTC, mastercoms approved these changes, later dismissed

2021-09-10 03:12 UTC, mastercoms commented on docs/next_steps/quick_fixes.md
> +Due to a bug in the game, the outlines for Scottish Resistance stickybombs only appears when objective outlines are enabled. You can fix this by adding `outlines=medium` to your `modules.cfg`.
@treacherousfiend Please add a note about DX8

2021-09-10 03:15 UTC, merged