Add support to translate echoes
mastercoms/tf2cfg pull request #570
Opened 2021-08-08 12:00 UTC by Tiagoquix

Opened as a draft pull request to wait the response of @mastercoms to decide if she prefers single person or third person, and singular or plural.

Currently, this has been translated in third person and in singular.

@mastercoms, if you're reading this and I haven't replied yet, and you prefer third person and singular, you can merge this.

2021-08-12 05:49 UTC, mastercoms requested changes

2021-08-12 05:49 UTC, mastercoms commented on dev/presets/package.sh
> +        printf "echo_lang;"
Move this back

2021-08-12 11:31 UTC, Tiagoquix commented
Done @mastercoms

2021-08-15 23:51 UTC, Tiagoquix commented
From my testings using ``preset_low;run_modules;r_flashlightdepthtexture 1;r_flashlightrender 1;r_flashlightmodels 1;r_flashlightculldepth 1;r_flashlightscissor 1;mat_supportflashlight 1``, to enable flashlight it only requires ``shadows_very_low`` and nothing more. Not tested on Very Low, but the flashlight should work too.

``mat_supportflashlight 1`` is necessary because the game doesn't set it automatically (it only sets when the game launches).

I'll add new commits soon.

2021-08-16 00:32 UTC, Tiagoquix commented
The flashlight module has been finalized.

@mastercoms This pull request is now ready for review.

2021-09-10 03:13 UTC, mastercoms approved these changes

2021-09-10 03:15 UTC, merged