Update linux.md
mastercoms/tf2cfg pull request #695
Opened 2022-12-22 13:30 UTC by colias-palaeno

- Added a warning for Steam Flatpak users (separate from the existing one for Wayland users) regarding using the system version of SDL2
- Fixed a dead link containing a Steam rules file for Anaincy

2022-12-22 14:49 UTC, mastercoms requested changes

2022-12-22 14:49 UTC, mastercoms commented on docs/os/linux.md
> +!!! warning
Add another line between the 2 warnings

2022-12-22 16:40 UTC, colias-palaeno commented on docs/os/linux.md
> +!!! warning
It's done. Should be fine to merge now

2022-12-22 18:54 UTC, getchoo commented
i don't think adding the warning for flatpak is the best way to go about this. while it is true that you need to give the flatpak permission to access the native library, it's a bit pointless since the flatpak version of steam already pins a (decently) up to date version of SDL from the runtime
```bash
$ realpath ~/.var/app/com.valvesoftware.Steam/data/Steam/ubuntu12_32/steam-runtime/pinned_libs_32/libSDL2-2.0.so.0
/home/seth/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/i386-linux-gnu/libSDL2-2.0.so.0.2400.1
```

i think a better option here would be to make a note that only removing the built-in version SDL from `Team Fortress 2/bin` is required for the flatpak version

2022-12-24 01:20 UTC, mastercoms approved these changes

2022-12-24 01:21 UTC, merged

2022-12-24 01:21 UTC, mastercoms commented
@getchoo PR welcome