Some gameplay related cvars changed
mastercoms/tf2cfg pull request #88
Opened 2019-07-30 22:20 UTC by Perkzitos

I changed some cvars because, in my opinion, the values that I choosed it's better for the gameplay.

download_all - because some community servers have custom sounds/models, like Freak Fortress 2 servers.

tf_hud_target_id_alpha - value 255 because it's better to see people info when playing (teammates or enemies if you are a Spy).

tf_medieval_thirdperson - value 0 because it's hard to trickstab when playing with the Spy and also when playing as Sniper with the Huntsman.

tf_dingalingaling and tf_dingalingaling_lasthit - value 1 for the two options because it will help newbies in the game.

2019-07-31 00:34 UTC, mastercoms requested changes

2019-07-31 00:34 UTC, mastercoms commented on config/mastercomfig/cfg/comfig/comfig.cfg
> +alias download download_all
The majority of players I feel will not need to download anything, since they don't go on custom servers. Long server download times has long been a pain point for regular users (https://www.teamfortress.tv/52468/dm-server-jointime-fix), and those who go on those speciality servers can change it for themselves.

2019-07-31 00:34 UTC, mastercoms commented on config/mastercomfig/cfg/comfig/comfig.cfg
> +tf_hud_target_id_alpha 255 // Transparency of target ID
I would rather this be a least somewhat translucent, so that you can see behind it, but still have enough visibility to read the values.

2019-07-31 00:34 UTC, mastercoms commented on config/mastercomfig/cfg/comfig/comfig.cfg
> +tf_medieval_thirdperson 0 // First person view in medieval mode
This one's a tough one. It's a hidden option that's very interesting. Most people don't know about it, but I can see why some people would not want it on.

2019-07-31 01:35 UTC, Perkzitos commented on config/mastercomfig/cfg/comfig/comfig.cfg
> +alias download download_all
Ok then, let's go left it with mapsonly.

2019-07-31 01:41 UTC, Perkzitos commented on config/mastercomfig/cfg/comfig/comfig.cfg
> +tf_hud_target_id_alpha 255 // Transparency of target ID
I do not agree. A teammate/enemy life's HUD is a very small information. And, this is a several information that you need to see it quickly, and if you put some transparency on it, it can't give good results. I believe transparency in this would not be necessary as it would not disrupt even 5% of the gameplay.

2019-07-31 01:47 UTC, Perkzitos commented on config/mastercomfig/cfg/comfig/comfig.cfg
> +tf_medieval_thirdperson 0 // First person view in medieval mode
It's a interesting option, and, "hidden". However, it's best to leave this option disabled.

2019-08-01 04:41 UTC, mastercoms commented on config/mastercomfig/cfg/comfig/comfig.cfg
> +tf_hud_target_id_alpha 255 // Transparency of target ID
Well, the default has been 100 in the game, even without the config and I haven't seen any people complain about the transparency.

2019-08-01 13:40 UTC, Perkzitos commented on config/mastercomfig/cfg/comfig/comfig.cfg
> +tf_hud_target_id_alpha 255 // Transparency of target ID
Alright then. I suggested this because I always used **tf_hud_target_id_disable_floating_health 1**, and transparency with this is not so good. But, I guess most people use the floating health, so, let's leave this on the value of 100, it's a good value.

2019-08-01 13:41 UTC, Perkzitos commented on config/mastercomfig/cfg/comfig/comfig.cfg
> +tf_medieval_thirdperson 0 // First person view in medieval mode
And what about this, mastercoms?

2019-08-01 13:41 UTC, mastercoms commented on config/mastercomfig/cfg/comfig/comfig.cfg
> +tf_medieval_thirdperson 0 // First person view in medieval mode
I would rather it be commented out, instead of forced off.

2019-08-01 13:42 UTC, mastercoms commented on config/mastercomfig/cfg/comfig/comfig.cfg
> +tf_hud_target_id_alpha 255 // Transparency of target ID
Remember to edit your file again: https://github.com/Perkzitos/mastercomfig/edit/patch-4/config/mastercomfig/cfg/comfig/comfig.cfg

2019-08-01 13:45 UTC, Perkzitos commented on config/mastercomfig/cfg/comfig/comfig.cfg
> +tf_medieval_thirdperson 0 // First person view in medieval mode
Alright. Leave it commented. And, for the next changelog, tell users who didn't like this setting on, to turn it off with the command. I suggest to leave it commented like this:

> tf_medieval_thirdperson 0 // First person view in medieval mode
> tf_medieval_thirdperson 1 // Third person view in medieval mode

2019-08-01 13:59 UTC, Perkzitos commented
mastercoms, I will close this pull request. There is anything else you want to say?

2019-08-01 13:59 UTC, mastercoms commented
There are still changes that I can merge from here, I don't think it should be closed.

2019-08-01 14:01 UTC, merged

2019-08-01 14:01 UTC, mastercoms commented
Thank you for your contribution to mastercomfig!