Some changes
mastercoms/tf2cfg pull request #99
Opened 2019-08-10 20:40 UTC by Perkzitos

2019-08-11 21:21 UTC, mastercoms requested changes

2019-08-11 21:21 UTC, mastercoms commented on config/mastercomfig/cfg/comfig/comfig.cfg
> +tf_mm_partyclient_debug 0 // Remove party debug output
Already off by default.

2019-08-11 21:21 UTC, mastercoms commented on config/mastercomfig/cfg/comfig/comfig.cfg
> +tf_party_keep_on_same_team 1 // Enforce parties being on the same team
Not implemented yet and can be changed in the menu, so we shouldn't be resetting it by default.

2019-08-11 21:21 UTC, mastercoms commented on config/mastercomfig/cfg/comfig/comfig.cfg
> +r_queued_decals 0 // Enforce disabling to prevent crashes
0 by default and not stored so no point in setting it.

2019-08-11 21:21 UTC, mastercoms commented on config/mastercomfig/cfg/comfig/comfig.cfg
Invalid AA mode.

2019-08-11 21:21 UTC, mastercoms commented on config/mastercomfig/cfg/comfig/comfig.cfg
> +cl_autoreload 1 // Auto reload clip
Already on by default and stored, so let's not reset it.

2019-08-11 21:21 UTC, mastercoms commented on config/mastercomfig/cfg/comfig/comfig.cfg
> +alias restore_comfig "exec autoexec"
This isn't necessarily just comfig, but the whole config, including the user's.

2019-08-11 21:21 UTC, mastercoms commented on config/mastercomfig/cfg/comfig/comfig.cfg
> +m_filter 1 // Average mouse input over two frames, more stable mouse input with high FPS variability
We shouldn't change any input settings. That's what flat mouse it for.

2019-08-12 15:41 UTC, Perkzitos commented on config/mastercomfig/cfg/comfig/comfig.cfg
> +tf_party_keep_on_same_team 1 // Enforce parties being on the same team
The command already exists. I know the function was not implemented yet, but, enabling it for the future may be a good cause?

2019-08-12 15:44 UTC, Perkzitos commented on config/mastercomfig/cfg/comfig/comfig.cfg
Invalid? comfig.cfg:
https://github.com/mastercoms/mastercomfig/blob/release/config/mastercomfig/cfg/comfig/comfig.cfg#L441

2019-08-14 04:30 UTC, mastercoms commented on config/mastercomfig/cfg/comfig/comfig.cfg
> +tf_party_keep_on_same_team 1 // Enforce parties being on the same team
Yeah but people will prefer setting it in the menu instead of having it reset and needing to put it in autoexec

2019-08-14 04:31 UTC, mastercoms commented on config/mastercomfig/cfg/comfig/comfig.cfg
That's for another combination, mat_antialias 8 can only be used with mat_aaquality 2

2019-08-16 01:24 UTC, Perkzitos commented
And what about the other things you haven't mentioned? Sorry for closing the pull request.

2019-08-16 02:52 UTC, mastercoms commented
Those are fine

2019-08-16 15:12 UTC, Perkzitos commented
> Those are fine

Alright. So, merge it?

2019-08-16 15:21 UTC, mastercoms commented
The file was not changed to include the requested changes. Only the conversation was marked as resolved.

2019-08-16 15:52 UTC, Perkzitos commented
> The file was not changed to include the requested changes. Only the conversation was marked as resolved.

And, would you change something from this commit that I made?

2019-09-02 15:01 UTC, mastercoms commented
Merged in https://github.com/mastercoms/mastercomfig/commit/c25ae42d6bc5a2a2ae5d41bdd4fd380bdd34f2d3.

2019-09-02 15:01 UTC, closed without merging